version: '3.8'

x-defaults: &default-backend
  restart: unless-stopped
  networks:
    - backend

services:
  # ------------------------- message broker -------------------------
  zookeeper:
    <<: *default-backend
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper-saga-pattern
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    <<: *default-backend
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-saga-pattern
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-saga-pattern:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # ------------------------- db's ------------------------
  mongodb-orders:
    <<: *default-backend
    container_name: mongodb-orders
    image: mongo:7.0-jammy
    ports:
      - "27000:27017"
    environment:
      MONGO_INITDB_DATABASE: orders

  mongodb-payments:
    <<: *default-backend
    container_name: mongodb-payments
    image: mongo:7.0-jammy
    ports:
      - "27002:27017"
    environment:
      MONGO_INITDB_DATABASE: payments

  mongodb-users:
    <<: *default-backend
    container_name: mongodb-users
    image: mongo:7.0-jammy
    ports:
      - "27003:27017"
    environment:
      MONGO_INITDB_DATABASE: users

networks:
  backend:
    driver: bridge