server:
  port: 8082

spring:
  application:
    name: payment-service

  kafka:
#    bootstrap-servers: http://localhost:9093
    consumer:
      bootstrap-servers: localhost:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

  data:
    mongodb:
      uri: mongodb://localhost:27002/payments

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka