server:
  port: 8761

spring:
  application:
    name: eureka-discovery-service

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka