server:
  port: 0

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://localhost:27003/users

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka